### ISSUE TITLE
[Event] Absolute Avarice (Great)

### ISSUE THREAD

**Issue by ben-lear** [AsdarDevelops/PokeRogue-Events#58]
### Event Name

Absolute Avarice

### Rarity Tier

Great

### Waves

11-179

### Description

Player must have at least 4 berries among its party for the encounter to spawn. A Greedent ambushes you and steals all berries from your entire party. It's about to eat them all, when it gives you an inquisitive look.

### Biomes

PLAINS, GRASS, TALL_GRASS, FOREST

### Options offered to the player

- [ ] Attack the Greedent
    - _You fight a Greedent boss with an omniboost._
    - _It has all berries that were stolen equipped on itself_
    - _At the end of the fight, each member of your party gains a Reviver Seed._
- [ ] Reason with it
    - _No fight_
    - _Your Pokemon regain 1-2 random berries that they had each lost._
- [ ] Let it have the food
    - _The Greedent chows down on all they berries (they are lost)_
    - _The Greedent offers to join your team._
    - _It has Passive unlocked, knows Thrash/Body Press/Stuff Cheeks/Slack Off._
    - _Letting the Greedent "join" does not affect meta progression other than counting as a catch for Nature/IV purposes (passive is not unlocked in dex)_

### Explanation/Notes on Design

Potential punishing event to Pickup/berry hoarding strats. But plenty of good outcomes from the event as well.

**Comment by AsdarDevelops** [comment]
> Your Pokemon regain 1-2 random berries that they had each lost.

This is a bit polarizing, here's my proposed changed:

Your Pokemon regain 33% of the amount of berries that they lost, rounded down. Meaning if they lost 1-2 berries, they don't gain them back. With 3, they gain 1 of them back.

I get it that this is a Pickup punishing Event, but I'd like there to be at least one option that makes the situation somewhat salvage for the person who might have 5 berries per Pokémon or so.

If it can be done, the number of berries recovered should be done taking the __total__ number of berries lost, meaning that if you have 3 PKMN with 5 berries each, you lose 10 berries, not 12. Alternatively, you can do it on each, but maybe then bump the % up to 45%, rounded down.
