### ISSUE TITLE
[Feature] Enhance Mystery Encounter phase to allow for multiple battle cycles

### ISSUE THREAD

**Issue by ben-lear** [AsdarDevelops/PokeRogue-Events#63]
Similar to https://github.com/AsdarDevelops/PokeRogue-Events/issues/55, we should also allow for the possibility of chaining multiple fights (and possibly reward phases) together as part of a single encounter.

For instance, you could have: a battle against an evil team grunt, then a leader, then a boss.
Or you could have, in a Safari Zone event: 3 back to back "encounters" of wild pokemon.

**Comment by AsdarDevelops** [comment]
I'm hyped for this util

**Comment by ben-lear** [comment]
This was completed as part of Safari Encounter PR
