### ISSUE TITLE
[Feature] Update “deep” copy logic for MEs to actually deep copy

### ISSUE THREAD

**Issue by ben-lear** [AsdarDevelops/PokeRogue-Events#71]
The pattern for MEs is that a master list of all MEs is maintained and pulled from whenever one spawns. However, a true deep copy is not made of the ME that gets picked, so certain data in the master list can be dirtied if it is updated on the chosen ME. Need to do some cleanup and have the full object deep copy instead of passing a shallow copy

**Comment by AsdarDevelops** [comment]
Gonna do a ping to see if this needs closing @ben-lear

**Comment by AsdarDevelops** [comment]
Closing this after confirmation from Imperial
