### ISSUE TITLE
[Event] Berries Abound (Common)

### ISSUE THREAD

**Issue by ben-lear** [AsdarDevelops/PokeRogue-Events#76]
### Event Name

Berries Abound

### Rarity Tier

Common

### Waves

11-179

### Description

You encounter a random wild Pokemon of the biome guarding a berry tree/bush. Nearly identical event to Fight or Flight, but the rewards are 1x berry for each party member instead of the item from Fight or Flight.

### Biomes

ANY (no need to select all)

### Options offered to the player

- [X] Fight
    - Random wild biome boss fight, based on the wave number. It's a shop full of 5 berry items, plus the lead pokemon will earn an extra X berries based on the wave number:
    - Waves 10-70: 2 berries
    - Waves 70-120: 4 berries
    - Waves 120-170: 5 berries
    - Waves 160-170: 7 berries
- [X] Steal
    - 75% chance to be caught by boss, same fight as option 1 but boss gets +1 to all stats at start. 25% chance to skip fight. If player has any Thief/Covet type moves, they automatically succeed.
    - Successfully stealing awards EXP like any other move/type check
- [X] Leave
    - No rewards or exp.

### Explanation/Notes on Design

Another common event, just a slight variation on Fight or Flight.

### Notes to Developers

To keep it more in line with "Fight or Flight", I'd propose the following changes:

Get more berries, as berries are worth less than a usual greatball tier item. You could give extra berries based on floor number, which would be applied to any random PKMN in your party that can hold them (they can always transfer afterwards).

**Comment by ben-lear** [comment]
> Waves 10-70: 1 extra berry (instead of an Great item from "Fight or Flight")
>Waves 70-120: 3 extra berries (instead of an Ultra item from "Fight or Flight")
> Waves 120-170: 5 extra berries (instead of Rogue item from "Fight or Flight")
>Waves 160-170: 10 extra berries (instead of Masterball item from "Fight or Flight")

I’m fine with this yeah

**Comment by AsdarDevelops** [comment]
Added my feedback to the issue so we don't forget
